name: Execute Tennis Notebook Femminile

on:
  schedule:
    - cron: '30 */3 * * *'  primo job ogni 3 ore e mezza
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install nbconvert
        pip install jupyter
        pip install ipykernel
        pip install --upgrade gdown  # Per scaricare file da Google Drive
        pip install requests pandas openpyxl
        pip install selenium
        pip install reportlab
        pip install beautifulsoup4
        pip install python-telegram-bot nest_asyncio
        pip install matplotlib scipy
        pip install gspread
        pip install pillow  # Per importare PIL
        pip install gspread_dataframe  # Per gestire Google Sheets

    - name: Execute Notebook
      run: |
        jupyter nbconvert --to notebook --execute ESECUZIONE_NOTEBOOK_TENNIS_W.ipynb --output executed_notebook.ipynb

  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Attendere prima di eseguire il secondo job
        run: sleep 600  # Attendere 10 minuti
        
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
  
      - name: Install dependencies
        run: |
          pip install nbconvert
          pip install jupyter
          pip install ipykernel
          pip install --upgrade gdown  # Per scaricare file da Google Drive
          pip install requests pandas openpyxl
          pip install selenium
          pip install reportlab
          pip install beautifulsoup4
          pip install python-telegram-bot nest_asyncio
          pip install matplotlib scipy
          pip install gspread
          pip install pillow  # Per importare PIL
          pip install gspread_dataframe  # Per gestire Google Sheets
  
      - name: Execute Notebook
        run: |
          jupyter nbconvert --to notebook --execute ESECUZIONE_NOTEBOOK_TENNIS_M.ipynb --output executed_notebook.ipynb
