name: Execute Tennis Notebooks ATP/WTA

on:
  schedule:
    - cron: '0 0/5 * * *'  # Esegui ogni 4 ore
  workflow_dispatch:

jobs:
  WTA_flow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install nbconvert
        pip install jupyter
        pip install ipykernel
        pip install --upgrade gdown  # Per scaricare file da Google Drive
        pip install requests pandas openpyxl
        pip install selenium
        pip install reportlab
        pip install beautifulsoup4
        pip install python-telegram-bot nest_asyncio
        pip install matplotlib scipy
        pip install gspread
        pip install pillow  # Per importare PIL
        pip install gspread_dataframe  # Per gestire Google Sheets

    - name: Execute WTA Notebook
      run: |
        jupyter nbconvert --to notebook --execute ESECUZIONE_NOTEBOOK_TENNIS_W.ipynb --output executed_notebook_wta.ipynb

    - name: Print output WTA notebook
      run: |
        cat executed_notebook_wta.ipynb

  ATP_flow:
    runs-on: ubuntu-latest
    needs: WTA_flow  # Attendere il completamento del job WTA
    steps:
    - name: Wait for 15 minutes
      run: sleep 900  # Pausa di 15 minuti

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install nbconvert
        pip install jupyter
        pip install ipykernel
        pip install --upgrade gdown  # Per scaricare file da Google Drive
        pip install requests pandas openpyxl
        pip install selenium
        pip install reportlab
        pip install beautifulsoup4
        pip install python-telegram-bot nest_asyncio
        pip install matplotlib scipy
        pip install gspread
        pip install pillow  # Per importare PIL
        pip install gspread_dataframe  # Per gestire Google Sheets

    - name: Execute ATP Notebook
      run: |
        jupyter nbconvert --to notebook --execute ESECUZIONE_NOTEBOOK_TENNIS_M.ipynb --output executed_notebook_atp.ipynb

    - name: Print output ATP notebook
      run: |
        cat executed_notebook_atp.ipynb
